version: "3.8"

services:
  mongo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=bootcamp
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
