import './globals.css';
import localFont from 'next/font/local';
import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap-icons/font/bootstrap-icons.css';
import StoreProvider from 'game/app/store/provider';
import Headers from 'game/app/components/layout/headers/page';
import Footer from 'game/app/components/layout/footer/page';

const geistSans = localFont({
    src: './fonts/GeistVF.woff',
    variable: '--font-geist-sans',
    weight: '100 900',
});

const geistMono = localFont({
    src: './fonts/GeistMonoVF.woff',
    variable: '--font-geist-mono',
    weight: '100 900',
});

export const metadata = {
    title: 'Game',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable}`}>
                <StoreProvider>
                    <Headers />
                    {children}
                    <Footer />
                </StoreProvider>
            </body>
        </html>
    );
}
